.TH "LookAtTargetController" 3 "Thu Jan 7 2016" "Version 2.0" "OculusRift" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LookAtTargetController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBTarget\fP"
.br
.ti -1c
.RI "bool \fBsmooth\fP = true"
.br
.ti -1c
.RI "float \fBdamping\fP = 6\&.0f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OculusRift from the source code\&.
