.TH "UIGameController" 3 "Thu Jan 7 2016" "Version 2.0" "OculusRift" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIGameController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShowInfo\fP ()"
.br
.ti -1c
.RI "void \fBHideInfo\fP ()"
.br
.ti -1c
.RI "void \fBRestartGame\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBEngineForceView\fP"
.br
.ti -1c
.RI "GameObject \fBRestartButton\fP"
.br
.ti -1c
.RI "GameObject \fBInfoButton\fP"
.br
.ti -1c
.RI "GameObject \fBInfoPanel\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBUIGameController\fP \fBruntime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OculusRift from the source code\&.
