.TH "CheckpointController" 3 "Thu Jan 7 2016" "Version 2.0" "OculusRift" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CheckpointController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCheckpoint\fP[] \fBCheckpointsList\fP"
.br
.ti -1c
.RI "\fBLookAtTargetController\fP \fBArrow\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OculusRift from the source code\&.
