.TH "Models/Helicopter/Scripts/ControlPanel.cs" 3 "Thu Jan 7 2016" "Version 2.0" "OculusRift" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models/Helicopter/Scripts/ControlPanel.cs \- Cette classe permet de capter un événement du clavier ou d'une manette\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBControlPanel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cette classe permet de capter un événement du clavier ou d'une manette\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for OculusRift from the source code\&.
