.TH "Models/Helicopter/Scripts Directory Reference" 3 "Thu Jan 7 2016" "Version 2.0" "OculusRift" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models/Helicopter/Scripts Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBControlPanel\&.cs\fP"
.br
.RI "\fICette classe permet de capter un événement du clavier ou d'une manette\&. \fP"
.ti -1c
.RI "file \fBHeliRotorController\&.cs\fP"
.br
.RI "\fICette classe permet de controler la rotation des rotors de l'hélicoptère\&. \fP"
.in -1c
