.TH "Models/Helicopter/Scripts/HeliRotorController.cs" 3 "Thu Jan 7 2016" "Version 2.0" "OculusRift" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models/Helicopter/Scripts/HeliRotorController.cs \- Cette classe permet de controler la rotation des rotors de l'hélicoptère\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHeliRotorController\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cette classe permet de controler la rotation des rotors de l'hélicoptère\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for OculusRift from the source code\&.
